version: "3.9"
services:

  frontend:
    image: city-builder-frontend:latest
    ports:
       - mode: host
         target: 4200
         published: 4200
    networks:
      - city-builder
  backend:
    image: city-builder-backend:latest
    ports:
       - mode: host
         target: 4444
         published: 4444
    networks:
      - city-builder

networks:
  city-builder: